# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: pre-commit-local
        name: Check django lint & migrations
        entry: bash -c "make codestyle && make check_migrations"
        language: system
        types:
          - python
        pass_filenames: false
        stages:
          - pre-push
exclude: "(.*)\\.mjs$" # Ignore all js module files
